server:
  port: 9050

spring:
  application:
    name: hooli-order-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定集群名称
        cluster-name: BJ
        metadata:
          version: v1
    sentinel:
      transport:
        # 配置sentinel控制台地址
        dashboard: localhost:8080
        # 指定和控制台通信的ip
        # 如不配置，会自动选择一个ip注册
        #client-ip: localhost

feign:
  sentinel:
    enabled: true
